development:
  sessions:
    default:
      uri: mongodb://localhost/wishywishy
production:
  sessions:
    default:
      uri: mongodb://squaredwishy:squaredwishy@kahana.mongohq.com:10021/wishywishy
localtest:
  sessions:
    default:
      uri: mongodb://localhost/wishywishytest
remotetest:
  sessions:
    default:
      uri: mongodb://tester:tester@kahana.mongohq.com:10022/wishywishytest
